INSERT INTO News VALUES (N'Ngô Thanh Vân tiếp tục đóng phim Hollywood', N'Ngô Thanh Vân đóng phần hai "The old guard" - series hành động minh tinh Charlize Theron đóng chính. Hôm 1/7, cô bày tỏ háo hức khi nhân vật của cô - Quỳnh, nữ chiến binh có siêu năng lực - trở lại trong phần hai, dự kiến khởi quay đầu năm 2022. Cô nói: "Tôi cảm ơn sự ủng hộ từ khán giả và mong nhân vật sẽ lợi hại hơn khi trở lại". Trên trang Maaction Cinema, đạo diễn Gina Prince-Bythewood cho biết phần hai sẽ bám sát tiểu thuyết nguyên tác. Trong đó, sự kiện Quỳnh trỗi dậy sẽ gây ra nhiều vấn đề. Cô ôm hận khi đồng đội Andy (Charlize Theron) đã không giải cứu cô suốt 500 mắc kẹt trong quan tài dưới đáy biển. "Phim cũng sẽ những câu chuyện bên lề mang đến rắc rối trên toàn thế giới. Kẻ phản diện không phải người bất tử, do đó sẽ là sự cân bằng tuyệt vời giữa hai phe", đạo diễn nói. The Old Guard. - phần một ra mắt vào tháng 7/2020 - kể câu chuyện về Andy. Cô dẫn đầu một nhóm lính đánh thuê gồm những người bất tử tồn tại gần 1.000 năm. Họ không biết tại sao mình bất tử, chỉ biết rằng những vết thương chí mạng cứ thế tự lành lặn không để lại dấu vết nào. Nhóm lính cứ thế sống qua hàng trăm năm cho đến khi, sự bất tử dần biến mất. Đến thế kỷ 17, Andy và Quỳnh bị tra tấn và kết tội là phù thủy. Andy chứng kiến Quỳnh bị nhốt vào một quan tài sắt và ném xuống biển, song không thể giải cứu. Sau khi trốn thoát, cô đi tìm Quỳnh hàng trăm năm nhưng mất dấu. Ngô Thanh Vân không xuất hiện nhiều trong phần một, nhưng để lại ấn tượng với khán giả và giới phê bình, nhất là trong cảnh kết phim. Biên kịch Greg Rucka nói với Polygon: "Tôi nghĩ những gì cô ấy làm với câu thoại duy nhất trong cảnh đó gây lạnh xương sống". Trên Instagram, Charlize Theron đăng ảnh hậu trường bên Ngô Thanh Vân, nói may mắn khi làm việc cùng cô. Trong truyện gốc, nhân vật của Ngô Thanh Vân là người Nhật Bản, có tên Noriko. Tuy nhiên, khi nhận vai, cô yêu cầu đổi thành tên Việt Nam và được ekip chấp thuận. Bên cạnh Charlize Theron và Ngô Thanh Vân, phim quy tụ dàn sao đa quốc tịch: Chiwetel Ejiofor, Marwan Kenzari, Matthias Schoenaerts, Luca Marinelli và KiKi Layne. Tác phẩm gây chú ý trên một nền tảng xem phim trực tuyến, vào top 10 phim do hãng sản xuất được xem nhiều nhất từ trước tới nay.', '2021-07-03 11:05:00', '2021-07-03 11:05:00', 0, 0)
INSERT INTO NewsAndImage VALUES (1, 1)

INSERT INTO News VALUES(N'''Luca'' - cuộc phiêu lưu kỳ thú ngày hè', N'Tác phẩm, do Casarosa đạo diễn, có bối cảnh tại thị trấn ven biển Italy vào thập niên 1950-1960, xoay quanh Luca (Jacob Tremblay lồng tiếng) - cậu bé thủy quái. Luca sống cùng gia đình dưới đáy biển, hàng ngày chăn nuôi đàn cá. Ngày nọ, cậu gặp Alberto (Jack Dylan Grazer lồng tiếng) - một thủy quái trạc tuổi sống tại đảo Isola del Mare. Nhờ Alberto, Luca khám phá được rằng loài của cậu khi lên bờ và ở trạng thái khô ráo sẽ chuyển sang hình dạng con người. Luca và Alberto nhanh chóng thành đôi bạn thân, cùng chia sẻ những điều thú vị về cuộc sống loài người và mơ ước có một chiếc xe máy để ngao du. Cha mẹ Luca phát hiện và phạt cậu phải đến ở cùng người bác tại vùng biển sâu. Luca trốn khỏi nhà, cùng Alberto tìm đến thị trấn Portorosso. Tại đây, hai cậu bé gặp người bạn mới Giulia (Emma Berman lồng tiếng). Cả ba hợp sức trong cuộc thi Portorosso Cup nhằm đánh bại kẻ chuyên bắt nạt Ercole (Saverio Raimondo lồng tiếng) và nhận phần thưởng để thực hiện mơ ước.', '2021-07-03 23:15:00', '2021-07-03 23:15:00', 0, 0)
INSERT INTO NewsAndImage VALUES (2, 2)
INSERT INTO NewsAndImage VALUES (2, 3)

INSERT INTO News VALUES(N'Ngồi ôtô xem phim thời dịch', N'Rạp chiếu phim cho người trên ôtô mọc ra nhiều ở Mỹ và châu Âu thời dịch, lan đến một số quốc gia châu Á, trong đó có Việt Nam. Rạp chiếu ngoài trời cho xe hơi đầu tiên và duy nhất ở Việt Nam khai trương ở Bãi Cháy Hạ Long (Quảng Ninh) hồi tháng 4, thu 50.000 đồng cho mỗi ôtô, không giới hạn số người trên xe. Trên fanpage ngày 28/6, đơn vị cập nhật lịch mở cửa vào tối thứ sáu, thứ bảy, chủ nhật hàng tuần, trong đó thứ bảy chiếu phim thiếu nhi. Ba phim hiện tại gồm: Godzilla đại chiến Kong (2/7), Bí mật thú cưng (3/7), Kingsman: Tổ chức hoàng kim (4/7). Các phim được chiếu là phim cũ, ra rạp cách đây vài năm. Đại diện đơn vị cho biết từ khi mở dịch vụ, ngày cao nhất họ đón 100 xe, gần đây khách đến xem lai rai do dịch phức tạp. Chưa thành công nhưng đây là hướng đi mới trong bối cảnh các rạp phải đóng cửa. Nhà báo Nguyên Minh - người theo dõi hoạt động điện ảnh nhiều năm - đánh giá mô hình này hiệu quả ở các đô thị loại hai, loại ba, nơi có tiềm năng du lịch, mặt bằng rộng. The Guardian nhận định dịch vụ xem phim cho khách trên ôtô đang mọc lên khắp thế giới để thỏa mãn cơn khát giải trí của người dân. Hiện nước Đức có hơn 20 rạp trong khi con số này ở Mỹ lên đến 300. Iran, Philippines cũng mở rạp đầu tiên từ năm ngoái, khi dịch bùng phát cao điểm. Trang Manila Times cho biết vào những ngày cuối tuần, nhiều khán giả trẻ, các gia đình có con nhỏ lái xe từ thủ đô Malina đến San Fernando để trải nghiệm. Nhiều người trả lời kênh GMA TV rằng họ thích xem phim ngoài trời hơn là ở nhà theo dõi kênh Netflix. Nam diễn viên Allen Dizon, nhà báo Nicolette Henson-Hizon và nhiều người nổi tiếng ở Philippines từng ủng hộ dịch vụ. Cây bút Steve Rose của The Guardian viết: "Rạp chiếu phim cho ôtô ngoài trời là thế giới tuyệt vời nhất thời dịch: bạn đang ra khỏi nhà nhưng không nhất thiết phải ra khỏi ôtô, bạn ở cùng những người khác nhưng yên tâm tách biệt".', '2021-07-03 23:17:00', '2021-07-03 23:17:00', 0, 0)
INSERT INTO NewsAndImage VALUES (3, 4)
INSERT INTO NewsAndImage VALUES (3, 5)

INSERT INTO News VALUES(N'''Tam Quốc'' vào top phim Hoa ngữ dở nhất', N'"Chân Tam Quốc vô song", phim do Cổ Thiên Lạc đóng chính, vào danh sách phim Hoa ngữ dở nhất nửa đầu năm nay. Trang Sohu chọn những tác phẩm điện ảnh bị khán giả chê nhiều nhất, trong đó có "Chân Tam Quốc vô song" - phim chuyển thể game của Nhật Bản. Tác phẩm được đầu tư 40 triệu USD, quy tụ dàn diễn viên nổi tiếng Cổ Thiên Lạc, Cổ Lực Na Trát, Vương Khải, Hàn Canh... song doanh thu ở rạp chỉ đạt khoảng 22 triệu nhân dân tệ (3,4 triệu USD). Nhiều khán giả chê kỹ xảo phim "ảo, rẻ tiền". Phim hài "Overall Planning" nhận chỉ trích của khán giả khi dùng tên tuổi tài tử Thẩm Đằng để câu khách. Đoàn phim giới thiệu anh "diễn xuất đặc biệt" nhưng trong phim chỉ có ảnh của Thẩm Đằng, còn đóng chính là Trương Huệ Văn, Hoàng Tài Luân. Trang 163 nhận xét cách làm này lừa dối, thiếu tôn trọng khán giả. Phim nhận 3/10 điểm trên diễn đàn Douban.', '2021-07-03 23:23:00', '2021-07-03 23:23:00', 0, 0)
INSERT INTO NewsAndImage VALUES (4, 6)
INSERT INTO NewsAndImage VALUES (4, 7)

INSERT INTO News VALUES(N'''Lupin 2'' - siêu đạo chích trở lại', N'Lupin là phim Pháp, dựa trên loạt truyện trinh thám nổi tiếng Arsene Lupin của tác giả Maurice Leblanc. Nhân vật chính - Arsene Lupin (Omar Sy) - là siêu đạo chích có tài hóa trang, chuyên trộm đồ của giới nhà giàu bằng những kế hoạch tinh vi. Phần một được giới chuyên môn đánh giá 98 % trên Rotten Tomatoes. Variety nhận xét tác phẩm là "phim xuất sắc đầu 2021 của Netflix, với kịch bản lớp lang và thông minh, có khả năng đánh lừa người xem liên tục". Sang mùa thứ hai, Arsene Lupin bị trùm tội phạm Hubert Pellegrini (Hervé Pierre) phát hiện danh tính. Gã lên kế hoạch bắt cóc con trai của Lupin là Raoul Diop (Etan Simon) khi cả gia đình anh đang đi du lịch. Người vợ là Claire (Ludivine Sagnier) phải "bán đứng" chồng cũ để cứu con trai, Lupin cũng lao vào hành trình nguy hiểm nhằm tiêu diệt Hubert Pellegrini. Bên cạnh sự truy đuổi của trùm tội phạm, Lupin còn bị thanh tra Youssef Guedira (Soufiane Guerrab) khám phá ra thân phận thật. Rơi vào tầm ngắm của hai thế lực, anh phải cùng người bạn thân Benjamin Ferel (Antoine Gouy) bỏ trốn, đồng thời vạch ra kế hoạch khác để trừng trị kẻ thù. Tác phẩm gay cấn ngay những phút đầu tiên khi con trai Lupin bị bắt cóc, khiến anh ngay lập tức phải lên kế hoạch tìm cậu bé. Càng về sau, phim càng kịch tính khi Hubert liên tục đối đầu với Lupin, đổ tội cho anh việc trộm cắp và giết người, khiến anh trở thành cái tên bị truy nã. Hubert được hé lộ không chỉ là một tỷ phú xấu tính mà còn có liên quan đến đường dây mua bán vũ khí xuyên quốc gia với hàng loạt âm mưu. Trong phần phim trước, những đoạn hồi tưởng tập trung nhiều vào mối quan hệ giữa cha của Lupin và trùm tội phạm Hubert, những ân oán của cả hai ảnh hưởng đến tính cách và tâm lý Lupin. Ở phần mới, câu chuyện tập trung vào Lupin và người vợ cũ từ khi còn nhỏ, cách hai người quen biết đến khi tiến đến hôn nhân. Phim có kịch bản lắt léo, các cú twist cài cắm xuyên suốt. Những pha móc túi, hóa trang, làm đồ giả, đến việc sử dụng công nghệ để đánh lừa người khác... được khắc họa kịch tính. Phim dẫn dắt khán giả đi theo hai tuyến hiện tại và quá khứ, qua đó xây dựng chân dung về Lupin và hành trình khiến anh dần trở thành một "bậc thầy trộm cắp".', '2021-07-03 23:32:00', '2021-07-03 23:32:00', 0, 0)
INSERT INTO NewsAndImage VALUES (5, 8)
INSERT INTO NewsAndImage VALUES (5, 9)
